### ISSUE TITLE
Incorrect radius for hyper_fit

### ISSUE THREAD

**Issue by marian42** [AlliedToasters/circle-fit#1]
Hi, thank you for this useful module!

With hyper_fit, I found that I get a very good center point, but the radius seems to be off.

    center_x, center_y, radius, _ = cf.hyper_fit(points)
    radius2 = np.average(np.linalg.norm(points - [center.x, center.y], axis=1))

The line above shows how I calculate the correct radius, this fits the supplied data very well.
Let me know if you need additional details.

**Comment by jeremyroy** [comment]
I am also having this issue.  Marian42's pull request fixed it and should be merged.
