### ISSUE TITLE
Getting negative x, y coordinates

### ISSUE THREAD

**Issue by agneet42** [AlliedToasters/circle-fit#13]
Hi, I am trying to generate `xc, yc, r, sigma = taubinSVD(point_coordinates)` , `point_coordinates` is a 2D list of [x,y] co-ordinates. However, in some cases I am getting xc, yc as negative values (all my coordinates are positive, basically pixel values) or very far away from the centroid of the points. I am wondering why?

**Comment by nup002** [comment]
It may be that your data is too noisy to be fitted. Can you post the data
that fails to fit with TaubinSVD?

**Comment by agneet42** [comment]
@nup002 looks like it. My data points are basically pixels denoting a certain object in the image, hence they are very dense in nature. 

Example - `[[468, 312], [468, 313], [468, 352], [468, 353], [468, 354], [468, 355], [468, 356], [468, 357], [468, 358], [468, 359], [468, 360], [468, 361], [468, 362], [468, 363], [468, 364], [468, 365], [468, 366], [468, 367], [468, 368], [468, 369], [468, 370], [468, 371], [468, 372], [468, 373], [468, 374], [468, 375], [468, 376], [468, 377], [468, 378], [468, 379], [468, 380], [468, 381], [468, 382], [468, 383], [468, 384], [468, 385], [469, 312], [469, 313], [469, 314], [469, 315], [469, 324], [469, 325], [469, 326], [469, 327], [469, 328], [469, 329], [469, 330], [469, 331], [469, 332], [469, 333], [469, 334], [469, 335], [469, 336], [469, 337], [469, 338], [469, 339], [469, 340], [469, 341], [469, 342], [469, 343], [469, 344], [469, 345], [469, 346], [469, 347], [469, 348], [469, 349], [469, 350], [469, 351], [469, 352], [469, 353], [469, 354], [469, 355], [469, 356], [469, 357], [469, 358], [469, 359], [469, 360], [469, 361], [469, 362], [469, 363], [469, 364], [469, 365], [469, 366], [469, 367], [469, 368], [469, 369], [469, 370], [469, 371], [469, 372], [469, 373], [469, 374], [469, 375], [469, 376], [469, 377], [469, 378], [469, 379], [469, 380], [469, 381], [469, 382], [469, 383], [469, 384], [469, 385], [469, 386], [470, 312], [470, 313], [470, 314], [470, 315], [470, 316], [470, 317], [470, 321], [470, 322], [470, 323], [470, 324], [470, 325], [470, 326], [470, 327], [470, 328], [470, 329], [470, 330], [470, 331], [470, 332], [470, 333], [470, 334], [470, 335], [470, 336], [470, 337], [470, 338], [470, 339], [470, 340], [470, 341], [470, 342], [470, 343], [470, 344], [470, 345], [470, 346], [470, 347], [470, 348], [470, 349], [470, 350], [470, 351], [470, 352], [470, 353], [470, 354], [470, 355], [470, 356], [470, 357], [470, 358], [470, 359], [470, 360], [470, 361], [470, 362], [470, 363], [470, 364], [470, 365], [470, 366], [470, 367], [470, 368], [470, 369], [470, 370], [470, 371], [470, 372], [470, 373], [470, 374], [470, 375], [470, 376], [470, 377], [470, 378], [470, 379], [470, 380], [470, 381], [470, 382], [470, 383], [470, 384], [470, 385], [470, 386], [470, 387], [471, 303], [471, 304], [471, 305], [471, 306], [471, 307], [471, 308], [471, 309], [471, 310], [471, 311], [471, 312], [471, 313], [471, 314], [471, 315], [471, 316], [471, 317], [471, 318], [471, 319], [471, 321], [471, 322], [471, 323], [471, 324], [471, 325], [471, 326], [471, 327], [471, 328], [471, 329], [471, 330], [471, 331], [471, 332], [471, 333], [471, 334], [471, 335], [471, 336], [471, 337], [471, 338], [471, 339], [471, 340], [471, 341], [471, 342], [471, 343], [471, 344], [471, 345], [471, 346], [471, 347], [471, 348], [471, 349], [471, 350], [471, 351], [471, 352], [471, 353], [471, 354], [471, 355], [471, 356], [471, 357], [471, 358], [471, 359], [471, 360], [471, 361], [471, 362], [471, 363], [471, 364], [471, 365], [471, 366], [471, 367], [471, 368], [471, 369], [471, 370], [471, 371], [471, 372], [471, 373], [471, 374], [471, 375], [471, 376], [471, 377], [471, 378], [471, 379], [471, 380], [471, 381], [471, 382], [471, 383], [471, 384], [471, 385], [471, 386], [471, 387], [472, 303], [472, 304], [472, 305], [472, 306], [472, 307], [472, 308], [472, 309], [472, 310], [472, 311], [472, 312], [472, 313], [472, 314], [472, 315], [472, 316], [472, 317], [472, 318], [472, 319], [472, 320], [472, 321], [472, 322], [472, 323], [472, 324], [472, 325], [472, 326], [472, 327], [472, 328], [472, 329], [472, 330], [472, 331], [472, 332], [472, 333], [472, 334], [472, 335], [472, 336], [472, 337], [472, 338], [472, 339], [472, 340], [472, 341], [472, 342], [472, 343], [472, 344], [472, 345], [472, 346], [472, 347], [472, 348], [472, 349], [472, 350], [472, 351], [472, 352], [472, 353], [472, 354], [472, 355], [472, 356], [472, 357], [472, 358], [472, 359], [472, 360], [472, 361], [472, 362], [472, 363], [472, 364], [472, 365], [472, 366], [472, 367], [472, 368], [472, 369], [472, 370], [472, 371], [472, 372], [472, 373], [472, 374], [472, 375], [472, 376], [472, 377], [472, 378], [472, 379], [472, 380], [472, 381], [472, 382], [472, 383], [472, 384], [472, 385], [472, 386], [472, 387], [473, 303], [473, 304], [473, 305], [473, 306], [473, 307], [473, 308], [473, 309], [473, 310], [473, 311], [473, 312], [473, 313], [473, 314], [473, 315], [473, 316], [473, 317], [473, 318], [473, 319], [473, 320], [473, 321], [473, 322], [473, 323], [473, 324], [473, 325], [473, 326], [473, 327], [473, 328], [473, 329], [473, 330], [473, 331], [473, 332], [473, 333], [473, 334], [473, 335], [473, 336], [473, 337], [473, 338], [473, 339], [473, 340], [473, 341], [473, 342], [473, 343], [473, 344], [473, 345], [473, 346], [473, 347], [473, 348], [473, 349], [473, 350], [473, 351], [473, 352], [473, 353], [473, 354], [473, 355], [473, 356], [473, 357], [473, 358], [473, 359], [473, 360], [473, 361], [473, 362], [473, 363], [473, 364], [473, 365], [473, 366], [473, 367], [473, 368], [473, 369], [473, 370], [473, 371], [473, 372], [473, 373], [473, 374], [473, 375], [473, 376], [473, 377], [473, 378], [473, 379], [473, 380], [473, 381], [473, 382], [473, 383], [473, 384], [473, 385], [473, 386], [473, 387], [474, 303], [474, 304], [474, 305], [474, 306], [474, 307], [474, 308], [474, 309], [474, 310], [474, 311], [474, 312], [474, 313], [474, 314], [474, 315], [474, 316], [474, 317], [474, 318], [474, 319], [474, 320], [474, 321], [474, 322], [474, 323], [474, 324], [474, 325], [474, 326], [474, 327], [474, 328], [474, 329], [474, 330], [474, 331], [474, 332], [474, 333], [474, 334], [474, 335], [474, 336], [474, 337], [474, 338], [474, 339], [474, 340], [474, 341], [474, 342], [474, 343], [474, 344], [474, 345], [474, 346], [474, 347], [474, 348], [474, 349], [474, 350], [474, 351], [474, 352], [474, 353], [474, 354], [474, 355], [474, 356], [474, 357], [474, 358], [474, 359], [474, 360], [474, 361], [474, 362], [474, 363], [474, 364], [474, 365], [474, 366], [474, 367], [474, 368], [474, 369], [474, 370], [474, 371], [474, 372], [474, 373], [474, 374], [474, 375], [474, 376], [474, 377], [474, 378], [474, 379], [474, 380], [474, 381], [474, 382], [474, 383], [474, 384], [474, 385], [474, 386], [474, 387], [474, 388], [475, 303], [475, 304], [475, 305], [475, 306], [475, 307], [475, 308], [475, 309], [475, 310]]`

I think it is not able to fit the circle correctly for this reason.

**Comment by nup002** [comment]
The data you posted looks like this:
![Screenshot 2023-01-17 140658](https://user-images.githubusercontent.com/15835242/212907028-3020f5d6-f352-4a8f-b4ec-abba889103aa.jpg)

It's just a block of points quite evenly spaced. There is no hint of circularity here, so naturally circle fitting will not give you any reasonable result. What exactly are you trying to do? Pehaps I can help if I understand your problem.

**Comment by agneet42** [comment]
@nup002 you are correct. My data points are basically pixel coordinates, which describe a given object. Hence, the object are so dense in nature. My use-case was to fit a circle , given this object's pixel coordinates. I have now come up with an alternate way of approximating that. Thank you for you insights! Appreciate it.
