### ISSUE TITLE
Bug: Incorrect fit hyperLSQ in 0.2.0.

### ISSUE THREAD

**Issue by Kutabu** [AlliedToasters/circle-fit#15]
In 0.2.0 the hyperLSQ() does no correct fit. During the re-coding between 0.1.3. an 0.2.0. two variables were swapped. In code line 501 and 502 the definition of x and y is incorrect. Correct is 
X = 0
Y = A0

I compared the code and in 0.1.3. the variables are correct. The error leads to no iteration in the following for loop (line 503).

I run into this error, because I updated the code via PIP recently and my openCV based fit did not work anymore. When using a lot of points, this is barly visible, but it leads to a massive error, when using only a few points, that are not distributed evenly on the circle. I attached an example that illustrates the error.
![X and Y](https://user-images.githubusercontent.com/125028940/218082495-d06d9f71-46ee-497b-89ae-3f84bb2ec9e5.PNG)
![Example](https://user-images.githubusercontent.com/125028940/218082838-285bd996-ec53-4d34-a902-c815bd302b83.PNG)

**Comment by nup002** [comment]
Hi Kutabu,
Thanks for noticing this bug. I have submitted a pull request that fixes the problem. @AlliedToasters will have to merge it and publish a new version on pypi.

**Comment by nup002** [comment]
The pull request to fix this problem has been merged, we are avaiting @AlliedToasters to publish a new version of the package to PyPi.

**Comment by Kutabu** [comment]
Thanks! :-)

**Comment by AlliedToasters** [comment]
@nup002 @Kutabu the change has been incorporated in v0.2.1, I will reopen ticket if the issue persists!
