### ISSUE TITLE
Import matplotlib inside plot_data_circle function

### ISSUE THREAD

**Issue by mieszkokl** [AlliedToasters/circle-fit#6]
Would it be possible to move matplotlib import statement to the plot_data_circle function?
I want to deploy an application using pyinstaller and I would have to deploy a whole matplotlib library also to run circle fit. In my opinion it's unnecessary overhead. I'm not using plot function at all, so I don't need a matplotlib, but when it's not deployed application crashes on circle_fit import.
If you don't mind I can propose changes in a pull request.

**Comment by AlliedToasters** [comment]
Sure, please make the change and open a pull request!

**Comment by AlliedToasters** [comment]
Here's the proposed change @mieszkokl, will merge and release soon

**Comment by nup002** [comment]
This feature has been merged.
